// Opencode hook generator.
//
// Writes a plugin JS file at .opencode/plugins/reversa-chronicler.js.
// Plugin uses the `tool.execute.after` event to spawn the runner as a
// child process with the affected file paths.
//
// The plugin file is owned by Reversa — entire file is created/deleted.
// (Unlike shared config files, plugins are per-feature.)

import { existsSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const PLUGIN_REL = '.opencode/plugins/reversa-chronicler.js';

function buildPlugin(runnerPath) {
  return `// Auto-generated by \`npx reversa add-hooks --engine opencode\`.
// Manages the Chronicler queue based on Opencode tool execution events.
// Removed by \`npx reversa remove-hooks --engine opencode\` or \`npx reversa uninstall\`.

import { spawn } from 'node:child_process';

const RUNNER = ${JSON.stringify(runnerPath)};

function invokeRunner(phase, payload) {
  const child = spawn('node', [RUNNER, '--phase', phase, '--engine', 'opencode', '--tool', payload?.tool ?? 'unknown'], {
    stdio: ['pipe', 'inherit', 'inherit'],
    detached: false,
  });
  try {
    child.stdin.write(JSON.stringify(payload ?? {}));
    child.stdin.end();
  } catch { /* swallow */ }
}

export default {
  'tool.execute.before': async ({ tool, input }) => {
    invokeRunner('pre', { tool, tool_input: input });
  },
  'tool.execute.after': async ({ tool, input, output }) => {
    invokeRunner('post', { tool, tool_input: input, output });
  },
};
`;
}

export default {
  id: 'opencode',
  name: 'Opencode',

  describe() {
    return 'Installs plugin .opencode/plugins/reversa-chronicler.js (tool.execute.before/after)';
  },

  generate({ projectRoot, runnerPath }) {
    const target = join(projectRoot, PLUGIN_REL);
    return {
      files: [{ path: target, content: buildPlugin(runnerPath) }],
      summary: [
        `Will write to: ${PLUGIN_REL}`,
        `  Plugin spawns runner via child_process on tool.execute.before/after.`,
      ].join('\n'),
    };
  },

  remove({ projectRoot }) {
    const target = join(projectRoot, PLUGIN_REL);
    const result = { removed: [], cleaned: [] };
    if (existsSync(target)) {
      try { unlinkSync(target); result.removed.push(target); }
      catch { /* swallow */ }
    }
    return result;
  },
};
